### ISSUE TITLE
Is this supposed to be working even if the web page is closed?

### ISSUE THREAD

**Issue by behrad** [Lorti/web-push-notifications#1]

**Comment by Lorti** [comment]
Can you specify your question?
The service worker runs even when the web page is closed. If you close your user agent, however, the service worker pauses it's execution.

**Comment by behrad** [comment]
the sample is not working properly on Chrome 62 on my Mac on localhost!
It only showed the notification popup for the first time, but in later runs  i noticed worker is receiving the push, but waitUntil is not calling showNotification!!!

**Comment by Lorti** [comment]
It is working for me on Chrome 62 on Sierra...

If you send the same notification again, it probably won't show for UX reasons. Have you tried using different tags to distinguish between the notifications?
